### PR TITLE
GitHub Actions: Automatically build Docker image

### PR DESCRIPTION
**Pull request by sim1**
Add DOCKER_TOKEN with value from https://hub.docker.com/settings/security to https://github.com/matrix-discord/mx-puppet-discord/settings/secrets

### CODE REVIEW

**Comment by Sorunome** [comment]
All the others auto-build docker images on dockerhub already, so why is this needed here?

**Comment by sim1** [comment]
GitHub Actions has a smaller delay/is more consistent from experience, but please, feel free to setup either.

**Comment by Sorunome** [comment]
It is already on docker hub, as stated in the readme. https://hub.docker.com/r/sorunome/mx-puppet-discord

**Comment by sim1** [comment]
Please enable automatic builds on docker hub then, since the latest update
tag is a 1 month old image.

**Pull request closed without merging**
