### PR TITLE
Add a nice badge for the support chat

### PR DESCRIPTION
**Pull request by anoadragon453**
Adds a nicer link to the support chat with live user count and everything. Analogous to [what we do for Dendrite](https://github.com/matrix-org/dendrite).

Guest access will need to be allowed for the room before the user count can be shown.

### CODE REVIEW

**Comment by Sorunome** [comment]
Thought of doing that but it just says "guests not allowed"

**Comment by anoadragon453** [comment]
> Guest access will need to be allowed for the room before the user count can be shown.

?

**Comment by Sorunome** [comment]
oh, woops. What downsides are with guest access, though?

/me is worried about a channel getting out of control

**Comment by anoadragon453** [comment]
You can peek the room and join if you know the address (which I think is the point of putting it on a github repo). It will not publish it to the room directory.

**Comment by anoadragon453** [comment]
:D?

**Pull request merged**
